spring:
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/diplom
    username: postgres
    password: 123
  flyway:
    baseline-on-migrate: true
    validateOnMigrate: false